import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import SideBar from "./components/sidebar";
import ContentCont from "./components/contentcontainer";
import NavBar from './components/content/navbar'
import Dashboard from './components/content/dashboard'
import UserReg from './user_regform'
import firebase from '../firebase/initfirebase'

firebase()

export default function Home() {
  return (
    <div>
      <Head>
        <title>NPMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
      <ContentCont component={<DashLayout />}/>
  
    </div>
  )
}

const DashLayout = () => {
  return (
    <div>
      <NavBar />
      <Dashboard />
      {/* <UserReg /> */}
    </div>
  );
};
